# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d0ca4ba8d8fef1bbae56e96b5f45d83c33da8ddd5d0faef73bc4cf14b661dacf5eace83d7e9a5ba3892b00011591a166b269adbf895f5ab9fbee42caa5cc3c5

test:
  secret_key_base: 068aeffdc059a7eb2b6944a2d2bb5b14d95decdf727fa5e60bb9f7da1839c4486b4975ca18918e2e98cc204097d93b7f0a37022b2a2c494954766599bcc2feeb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
